# Generated by Django 4.1.2 on 2022-10-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='posts/')),
                ('discription', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.ManyToManyField(to='posts.posttype')),
            ],
        ),
    ]
