# Generated by Django 4.1.2 on 2022-10-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_projects_services_team_delete_post_delete_posttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='number',
        ),
    ]
