# Generated by Django 4.1.2 on 2022-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkdin',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(default='.', max_length=255),
        ),
    ]
