# Generated by Django 4.1.2 on 2022-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='references/')),
                ('discription', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.png', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='default.png', upload_to='services/'),
        ),
    ]
