# Generated by Django 4.1.2 on 2022-11-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_references_alter_projects_image_alter_services_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'PROJELER'},
        ),
        migrations.AlterModelOptions(
            name='references',
            options={'verbose_name_plural': 'REFERANSLAR'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'HİZMETLER'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'UZMANLAR'},
        ),
        migrations.AlterField(
            model_name='references',
            name='image',
            field=models.ImageField(null=True, upload_to='references/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkdin',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='whatsapp',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
