# Generated by Django 4.1.2 on 2022-11-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_projects_options_alter_references_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='references',
            options={'verbose_name_plural': 'Referanslar'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Hizmetler'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Uzmanlar'},
        ),
    ]
