# Generated by Django 4.1.2 on 2022-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_projects_options_alter_references_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ManyToManyField(to='posts.projects')),
            ],
            options={
                'verbose_name_plural': 'Galeri',
            },
        ),
    ]
