# Generated by Django 4.1.2 on 2022-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_galeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='project',
            field=models.ManyToManyField(to='posts.projects'),
        ),
        migrations.RemoveField(
            model_name='galeri',
            name='name',
        ),
        migrations.AddField(
            model_name='galeri',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
