# Generated by Django 4.1.2 on 2022-11-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_galeri_project_remove_galeri_name_galeri_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeri',
            new_name='Gallery',
        ),
    ]
